
package eu.glowacki.jaxws.client.addressing.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AddressingException", targetNamespace = "http://glowacki.eu/addressing")
public class AddressingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AddressingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AddressingException_Exception(String message, AddressingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AddressingException_Exception(String message, AddressingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eu.glowacki.jaxws.client.addressing.proxy.AddressingException
     */
    public AddressingException getFaultInfo() {
        return faultInfo;
    }

}
