
package eu.glowacki.jaxws.client.bigdata.standard.proxy;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBigDataStandard", targetNamespace = "http://glowacki.eu/big-data/standard")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBigDataStandard {


    /**
     * 
     * @return
     *     returns eu.glowacki.jaxws.client.bigdata.standard.proxy.BigData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://glowacki.eu/big-data/standard", className = "eu.glowacki.jaxws.client.bigdata.standard.proxy.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://glowacki.eu/big-data/standard", className = "eu.glowacki.jaxws.client.bigdata.standard.proxy.GetResponse")
    @Action(input = "http://glowacki.eu/big-data/standard/IBigDataStandard/getRequest", output = "http://glowacki.eu/big-data/standard/IBigDataStandard/getResponse")
    public BigData get();

}
