
package eu.glowacki.jaxws.client.onewayrobust.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOneWayRobust", targetNamespace = "http://glowacki.eu/one-way-robust")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOneWayRobust {


    /**
     * 
     * @param arg0
     * @throws ServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "trigger", targetNamespace = "http://glowacki.eu/one-way-robust", className = "eu.glowacki.jaxws.client.onewayrobust.proxy.Trigger")
    @ResponseWrapper(localName = "triggerResponse", targetNamespace = "http://glowacki.eu/one-way-robust", className = "eu.glowacki.jaxws.client.onewayrobust.proxy.TriggerResponse")
    @Action(input = "http://glowacki.eu/one-way-robust/IOneWayRobust/triggerRequest", output = "http://glowacki.eu/one-way-robust/IOneWayRobust/triggerResponse", fault = {
        @FaultAction(className = ServiceException_Exception.class, value = "http://glowacki.eu/one-way-robust/IOneWayRobust/trigger/Fault/ServiceException")
    })
    public void trigger(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException_Exception
    ;

}
