
package eu.glowacki.jaxws.client.onewayrobust.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OneWayRobustImplService", targetNamespace = "http://glowacki.eu/one-way-robust", wsdlLocation = "http://localhost:8080/one-way-robust?wsdl")
public class OneWayRobustImplService
    extends Service
{

    private final static URL ONEWAYROBUSTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ONEWAYROBUSTIMPLSERVICE_EXCEPTION;
    private final static QName ONEWAYROBUSTIMPLSERVICE_QNAME = new QName("http://glowacki.eu/one-way-robust", "OneWayRobustImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/one-way-robust?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ONEWAYROBUSTIMPLSERVICE_WSDL_LOCATION = url;
        ONEWAYROBUSTIMPLSERVICE_EXCEPTION = e;
    }

    public OneWayRobustImplService() {
        super(__getWsdlLocation(), ONEWAYROBUSTIMPLSERVICE_QNAME);
    }

    public OneWayRobustImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ONEWAYROBUSTIMPLSERVICE_QNAME, features);
    }

    public OneWayRobustImplService(URL wsdlLocation) {
        super(wsdlLocation, ONEWAYROBUSTIMPLSERVICE_QNAME);
    }

    public OneWayRobustImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ONEWAYROBUSTIMPLSERVICE_QNAME, features);
    }

    public OneWayRobustImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OneWayRobustImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IOneWayRobust
     */
    @WebEndpoint(name = "IOneWayRobustPort")
    public IOneWayRobust getIOneWayRobustPort() {
        return super.getPort(new QName("http://glowacki.eu/one-way-robust", "IOneWayRobustPort"), IOneWayRobust.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns IOneWayRobust
     */
    @WebEndpoint(name = "IOneWayRobustPort")
    public IOneWayRobust getIOneWayRobustPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://glowacki.eu/one-way-robust", "IOneWayRobustPort"), IOneWayRobust.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ONEWAYROBUSTIMPLSERVICE_EXCEPTION!= null) {
            throw ONEWAYROBUSTIMPLSERVICE_EXCEPTION;
        }
        return ONEWAYROBUSTIMPLSERVICE_WSDL_LOCATION;
    }

}
