package eu.glowacki.jaxws.api.addressing;

import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.soap.Addressing;

@WebService( //
		name = "IAddressing", //
		targetNamespace = "http://glowacki.eu/addressing" //
)
@Addressing( //
		enabled = true, //
		required = true //
)
public interface IAddressing {

	public static final String URI = "http://localhost:8080/addressing";

	// @WebMethod(action = "http://glowacki.eu/addressing")
	/**
	 * @Action annotation enables specifying custom identification of messages
	 *         instead of relying on autogenerated names
	 */
	@Action( //
			input = "http://glowacki.eu/addressing/AddressingRequest", //
			output = "http://glowacki.eu/addressing/AddressingResponse", //
			fault = { //
					@FaultAction(className = AddressingException.class, value = "http://glowacki.eu/addressing/AddressException") //
			} //
	)
	String addressing(String request) throws AddressingException;
}