
package eu.glowacki.jaxws.client.compositePeople.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPerson", targetNamespace = "http://glowacki.eu/composite-people")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPerson {


    /**
     * 
     * @param arg0
     * @return
     *     returns eu.glowacki.jaxws.client.compositePeople.proxy.PersonResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filter", targetNamespace = "http://glowacki.eu/composite-people", className = "eu.glowacki.jaxws.client.compositePeople.proxy.Filter")
    @ResponseWrapper(localName = "filterResponse", targetNamespace = "http://glowacki.eu/composite-people", className = "eu.glowacki.jaxws.client.compositePeople.proxy.FilterResponse")
    @Action(input = "http://glowacki.eu/composite-people/IPerson/filterRequest", output = "http://glowacki.eu/composite-people/IPerson/filterResponse")
    public PersonResponseMessage filter(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequestMessage arg0);

}
