
package eu.glowacki.jaxws.client.compositePeople.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonImplService", targetNamespace = "http://glowacki.eu/composite-people", wsdlLocation = "http://localhost:8080/composite-people?wsdl")
public class PersonImplService
    extends Service
{

    private final static URL PERSONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONIMPLSERVICE_EXCEPTION;
    private final static QName PERSONIMPLSERVICE_QNAME = new QName("http://glowacki.eu/composite-people", "PersonImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/composite-people?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONIMPLSERVICE_WSDL_LOCATION = url;
        PERSONIMPLSERVICE_EXCEPTION = e;
    }

    public PersonImplService() {
        super(__getWsdlLocation(), PERSONIMPLSERVICE_QNAME);
    }

    public PersonImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONIMPLSERVICE_QNAME, features);
    }

    public PersonImplService(URL wsdlLocation) {
        super(wsdlLocation, PERSONIMPLSERVICE_QNAME);
    }

    public PersonImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONIMPLSERVICE_QNAME, features);
    }

    public PersonImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPerson
     */
    @WebEndpoint(name = "IPersonPort")
    public IPerson getIPersonPort() {
        return super.getPort(new QName("http://glowacki.eu/composite-people", "IPersonPort"), IPerson.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns IPerson
     */
    @WebEndpoint(name = "IPersonPort")
    public IPerson getIPersonPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://glowacki.eu/composite-people", "IPersonPort"), IPerson.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONIMPLSERVICE_EXCEPTION!= null) {
            throw PERSONIMPLSERVICE_EXCEPTION;
        }
        return PERSONIMPLSERVICE_WSDL_LOCATION;
    }

}
