
package eu.glowacki.jaxws.client.composite.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IComposite", targetNamespace = "http://glowacki.eu/composite")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IComposite {


    /**
     * 
     * @param arg0
     * @return
     *     returns eu.glowacki.jaxws.client.composite.proxy.AddResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://glowacki.eu/composite", className = "eu.glowacki.jaxws.client.composite.proxy.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://glowacki.eu/composite", className = "eu.glowacki.jaxws.client.composite.proxy.AddResponse")
    @Action(input = "http://glowacki.eu/composite/IComposite/addRequest", output = "http://glowacki.eu/composite/IComposite/addResponse")
    public AddResponseMessage add(
        @WebParam(name = "arg0", targetNamespace = "")
        AddRequestMessage arg0);

}
